# Generated by Django 4.0.3 on 2022-03-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_choice_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creat_date',
            new_name='create_date',
        ),
    ]
